### ISSUE TITLE
Vue 项目性能优化 — 实践指南

### ISSUE THREAD

**Issue by 97194350hu** [ant-move/TechNews#2]
### [Vue 项目性能优化 — 实践指南](https://mp.weixin.qq.com/s/qgOJmA1dxB2wor6_fk8yxg)

>Vue 框架通过数据双向绑定和虚拟 DOM 技术，帮我们处理了前端开发中最脏最累的 DOM 操作部分， 我们不再需要去考虑如何操作 DOM 以及如何最高效地操作 DOM；但 Vue 项目中仍然存在项目首屏优化、Webpack 编译配置优化等问题，所以我们仍然需要去关注 Vue 项目性能方面的优化，使项目具有更高效的性能、更好的用户体验。本文是作者通过实际项目的优化实践进行总结而来，希望读者读完本文，有一定的启发思考，从而对自己的项目进行优化起到帮助。本文内容分为以下三部分组成：
     Vue 代码层面的优化；
     webpack 配置层面的优化；
     基础的 Web 技术层面的优化。

**Comment by xiaofuzi** [comment]
merged
